name: workout_log
description: Save workouts logs !

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.2.3+8

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.12.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.5
  sqflite: ^2.4.2+1
  uuid: ^4.5.3
  intl: ^0.20.2
  table_calendar: ^3.2.0
  flutter_slidable: ^4.0.3
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
  freezed: ^3.2.3
  sqflite_common_ffi: ^2.3.6

# to update icon run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - graphics/background.jpg
    - graphics/lightBackground.jpg
