name: workout_log
description: Save workouts logs !

# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.2.2+7

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  uuid: ^4.4.0
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_slidable: ^3.1.0
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

# to update icon run:
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - graphics/background.jpg
    - graphics/lightBackground.jpg
